### ISSUE TITLE
The image is rendered as inverted 180 degrees

### ISSUE THREAD

**Issue by jubinjacobthomas** [7dir/aframe-svgfile-component#1]
i tried to draw the map of alaska using this. But the map is inverted 180 degrees. If i change the rotation, nothing is getting displayed. Attached the image drawn
![capture](https://cloud.githubusercontent.com/assets/13308392/22285510/f1ede77e-e311-11e6-94e7-6702c2689283.PNG)

**Comment by 7dir** [comment]
@jubinjacobthomas I know
I should fix it next version

**Comment by morandd** [comment]
perhaps you're viewing the back face of the mesh when you rotate and the material is only set to render the front side

**Comment by 7dir** [comment]
updated
